#define  pitVolume   pitvolume
#define  pitHeight   pitheight
#define  spillPoints  spillpoints
#define  fillDepression filldepression
#define  meanSlope  meanslope
#define  flatBounds  flatbounds
#define  slpBounds  slpbounds
#define  setHillslopeCoeff   sethillslopecoeff
#define  initDiffCoeff   initdiffcoeff
#define  setKdMat   setkdmat
#define  MFDreceivers   mfdreceivers
#define  defineTIN   definetin

#define  pitVolume_   pitvolume_
#define  pitHeight_   pitheight_
#define  spillPoints_  spillpoints_
#define  fillDepression_ filldepression_
#define  meanSlope_  meanslope_
#define  flatBounds_  flatbounds_
#define  slpBounds_  slpbounds_
#define  setHillslopeCoeff_   sethillslopecoeff_
#define  initDiffCoeff_   initdiffcoeff_
#define  setKdMat_   setkdmat_
#define  MFDreceivers_   mfdreceivers_
#define  defineTIN_   definetin_

#define  _pitVolume   _pitvolume
#define  _pitHeight   _pitheight
#define  _spillPoints  _spillpoints
#define  _fillDepression  _filldepression
#define  _meanSlope  _meanslope
#define  _flatBounds  _flatbounds
#define  _slpBounds  _slpbounds
#define  _setHillslopeCoeff   _sethillslopecoeff
#define  _initDiffCoeff   _initdiffcoeff
#define  _setKdMat  _setkdmat
#define  _MFDreceivers  _mfdreceivers
#define  _defineTIN  _definetin

#define  _pitVolume_   _pitvolume_
#define  _pitHeight_   _pitheight_
#define  _spillPoints_  _spillpoints_
#define  _fillDepression_  _filldepression_
#define  _meanSlope_  _meanslope_
#define  _flatBounds_  _flatbounds_
#define  _slpBounds_  _slpbounds_
#define  _setHillslopeCoeff_   _sethillslopecoeff_
#define  _initDiffCoeff_   _initdiffcoeff_
#define  _setKdMat_   _setkdmat_
#define  _MFDreceivers_  _mfdreceivers_
#define  _defineTIN_   _definetin_
