#define  meanSlope  meanslope
#define  flatBounds  flatbounds
#define  slpBounds  slpbounds
#define  setDiffusionCoeff  setdiffusioncoeff
#define  explicitDiff  explicitdiff
#define  distributeHeight   distributeheight
#define  distributeVolume   distributevolume
#define  setHillslopeCoeff  sethillslopecoeff
#define  diffusionDT  diffusiondt
#define  minHeight   minheight
#define  pitData   pitdata
#define  MFDreceivers   mfdreceivers
#define  defineTIN   definetin
#define  defineGTIN   definegtin

#define  meanSlope_  meanslope_
#define  flatBounds_  flatbounds_
#define  slpBounds_  slpbounds_
#define  setDiffusionCoeff_   setdiffusioncoeff_
#define  explicitDiff_   explicitdiff_
#define  distributeHeight_   distributeheight_
#define  distributeVolume_   distributevolume_
#define  setHillslopeCoeff_   sethillslopecoeff_
#define  diffusionDT_  diffusiondt_
#define  minHeight_   minheight_
#define  pitData_   pitdata_
#define  MFDreceivers_   mfdreceivers_
#define  defineTIN_   definetin_
#define  defineGTIN_   definegtin_

#define  _meanSlope  _meanslope
#define  _flatBounds  _flatbounds
#define  _slpBounds  _slpbounds
#define  _setDiffusionCoeff   _setdiffusioncoeff
#define  _explicitDiff   _explicitdiff
#define  _distributeHeight   _distributeheight
#define  _distributeVolume   _distributevolume
#define  _setHillslopeCoeff   _sethillslopecoeff
#define  _diffusionDT  _diffusiondt
#define  _minHeight   _minheight
#define  _pitData   _pitdata
#define  _MFDreceivers  _mfdreceivers
#define  _defineTIN  _definetin
#define  _defineGTIN  _definegtin

#define  _meanSlope_  _meanslope_
#define  _flatBounds_  _flatbounds_
#define  _slpBounds_  _slpbounds_
#define  _setDiffusionCoeff_   _setdiffusioncoeff_
#define  _explicitDiff_   _explicitdiff_
#define  _distributeHeight_   _distributeheight_
#define  _distributeVolume_   _distributevolume_
#define  _setHillslopeCoeff_   _sethillslopecoeff_
#define  _diffusionDT_  _diffusiondt_
#define  _minHeight_   _minheight_
#define  _pitData_   _pitdata_
#define  _MFDreceivers_  _mfdreceivers_
#define  _defineTIN_   _definetin_
#define  _defineGTIN_   _definegtin_
